//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_WCF_Student_Class_Practice_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentId { get; set; }
        public string studentName { get; set; }
        public string studentEmail { get; set; }
        public int classId { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
