//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int MaSv { get; set; }
        public string TenSV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NSinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaLop { get; set; }
        public string UserNm { get; set; }
        public string Password { get; set; }
    
        public virtual tblClass tblClass { get; set; }
    }
}
