//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_Student_Class_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public @class()
        {
            this.students = new HashSet<student>();
        }
    
        public int classId { get; set; }
        public string className { get; set; }
    
        public virtual ICollection<student> students { get; set; }
    }
}
