//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Data.Entity;

//namespace WindowsStores.Models
//{
//    public class MoviesModel : DbContext
//    {
//        public MoviesModel() : base("name=ExamEntities")
//        {

//        }
//        public virtual DbSet<Genre> Genre { get; set; }
//        public virtual DbSet<Movie> Movie { get; set; }
//    }
//}